# Generated by Django 4.0.6 on 2022-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='cell',
            field=models.CharField(choices=[('1', 'media'), ('2', 'contact & sponsoring'), ('3', 'Events'), ('4', 'Gaming'), ('5', 'Formation')], default='media', max_length=500),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='day',
            field=models.CharField(choices=[('1', 'Premier jour'), ('2', 'Deuxième jour')], default='Premier jour', max_length=500),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='year',
            field=models.CharField(choices=[('1', '1er année'), ('2', '2ème année'), ('3', '3ème année'), ('4', '4ème année'), ('5', '5ème année')], default='1er année', max_length=500),
        ),
    ]
