# Generated by Django 4.0.6 on 2022-09-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_extenduser_cell_alter_extenduser_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='phone'),
        ),
    ]
