# Generated by Django 4.0.6 on 2022-09-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_extenduser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='psw',
            field=models.CharField(default=5555, max_length=350, verbose_name='psw'),
            preserve_default=False,
        ),
    ]
