# Generated by Django 4.0.6 on 2022-09-07 16:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last_name')),
                ('choices', multiselectfield.db.fields.MultiSelectField(choices=[('C++', 'C++'), ('Python', 'Python'), ('Web Dev', 'Web Dev'), ('UI/UX design', 'UI/UX design')], max_length=31)),
            ],
        ),
    ]
